drop table if exists dwd.dwd_sd_customer_appt_board;
create table if not exists dwd.dwd_sd_customer_appt_board(
id string comment '主键'
,pending_id string comment '待办ID'
,follow_id string comment '跟进ID'
,customer_id string comment '客户ID'
,dealer_code string comment '销售店代码'
,branch_code string comment '店铺代码'
,sales_adviser_code string comment '销售顾问代码'
,sales_adviser_name string comment '销售顾问姓名'
,sales_adviser_org_id string comment '销售顾问组织ID'
,prior_intn_vehicle_type_code string comment '优先意向车种代码'
,prior_intn_vehicle_type_name string comment '优先意向车种名称'
,prior_intn_vehicle_model_code string comment '优先意向车型代码'
,prior_intn_vehicle_model_name string comment '优先意向车型名称'
,prior_intn_vehicle_grade_code string comment '优先意向车等级代码'
,prior_intn_vehicle_grade_name string comment '优先意向车等级名称'
,prior_intn_vehicle_sfx_code string comment '优先意向车SFX代码'
,prior_intn_vehicle_color_code string comment '优先意向车颜色代码'
,prior_intn_vehicle_color_name string comment '优先意向车颜色名称'
,prior_intn_interior_color_code string comment '优先意向车内饰颜色代码'
,prior_intn_interior_color_name string comment '优先意向车内饰颜色名称'
,prior_intn_vehicle_pic_url string comment '优先意向车图片url'
,customer_name string comment '客户姓名'
,mobile_phone string comment '移动电话'
,mobile_phone_reverse string comment '移动电话(反向)'
,gender string comment '性别'
,appt_flag string comment '是否预约'
,arrive_purpose_code string comment '到店目的代码'
,arrive_purpose_name string comment '到店目的名称'
,schedule_arrive_begin_time string comment '计划到店开始时间'
,schedule_arrive_end_time string comment '计划到店结束时间'
,actual_arrive_begin_time string comment '实绩到店开始时间'
,actual_arrive_end_time string comment '实绩到店结束时间'
,arrive_duration bigint comment '到店时长'
,arrive_type string comment '到店类型'
,arrive_status string comment '到店状态'
,arrive_quantity bigint comment '到店人数'
,remark string comment '备注'
,del_flag bigint comment '删除标识'
,create_by string comment '创建者'
,create_time string comment '创建时间'
,update_by string comment '更新者'
,update_time string comment '更新时间'
,operate_type string comment '数据的修改类型:I--Insert,U--表示数据更改,D--表示数据删除,M--业务系统数据归档,A--初始全量加载'
,dl_batch_id string comment 'dl加载批次'
,extract_time string comment '抽取表时的系统时间（kafka-hbase）'
,load_time string comment '数据加载到DL的时间'
,source_system string comment '来源系统(dms共通,dms销售....)'
,insert_time string comment '数据写入时间(跑批时间)'
,biz_date string comment '分区字段'
,dwd_del_flag bigint comment 'dwd删除标识(operate_type,delete_flag,del_flag,deleteflag合并字段，0:未删除;1:删除)'
) comment '客户预约情况看板'
stored as parquet
tblproperties("parquet.compress"="snappy");



drop table if exists dwd.dwd_sd_clue_customer;
create table if not exists dwd.dwd_sd_clue_customer(
id string comment '主键'
,enquiry_customer_code string comment '咨询客户代码'
,dealer_code string comment '销售店代码'
,social_code string comment '社会代码'
,customer_type string comment '客户类型'
,customer_name string comment '客户姓名'
,address string comment '地址'
,postal_code string comment '邮编'
,landline_number string comment '座机号码'
,mobile_phone string comment '移动电话'
,mobile_phone_reverse string comment '移动电话(反向)'
,business_landline_number string comment '业务座机号码'
,fax_number string comment '传真号码'
,email1 string comment '邮箱1'
,email2 string comment '邮箱2'
,gender string comment '性别'
,birthday string comment '生日'
,sms_flag string comment '短信标识'
,mail_flag string comment '邮箱标识'
,contact_dm_flag string comment '是否使用DM联系'
,contact_home_flag string comment '是否使用家庭电话联系'
,contact_mobile_phone_flag string comment '是否使用手机联系'
,contact_sms_flag string comment '是否使用短信联系'
,contact_email_flag string comment '是否使用邮箱联系'
,wechat string comment '微信'
,qq string comment 'QQ'
,blog string comment '博客'
,del_time string comment '删除时间'
,remark string comment '备注'
,del_flag bigint comment '删除标识'
,create_by string comment '创建者'
,create_time string comment '创建时间'
,update_by string comment '更新者'
,update_time string comment '更新时间'
,region string comment '地区'
,row_create_function string comment '记录创建程序'
,row_update_function string comment '记录更新程序'
,row_lock_version string comment '记录锁定版本'
,strcdstaff string comment '店里的工作人员代码'
,sacode string comment 'SA码'
,employeename string comment '担当者'
,employeedepartment string comment '担当者部门'
,employeeposition string comment '担当者职位'
,proopecd string comment '处理对象'
,registflg string comment '注册标志'
,state_cd string comment '省代码'
,district_cd string comment '区域代码'
,city_cd string comment '城市代码'
,location_cd string comment '区域代码'
,nametitle_cd string comment '尊敬的代码'
,nametitle string comment '尊称'
,operate_type string comment '数据的修改类型:I--Insert,U--表示数据更改,D--表示数据删除,M--业务系统数据归档,A--初始全量加载'
,dl_batch_id string comment 'dl加载批次'
,extract_time string comment '抽取表时的系统时间（kafka-hbase）'
,load_time string comment '数据加载到DL的时间'
,source_system string comment '来源系统(dms共通,dms销售....)'
,insert_time string comment '数据写入时间(跑批时间)'
,biz_date string comment '分区字段'
,dwd_del_flag bigint comment 'dwd删除标识(operate_type,delete_flag,del_flag,deleteflag合并字段，0:未删除;1:删除)'
) comment '线索客户表'
stored as parquet
tblproperties("parquet.compress"="snappy");


