drop table if exists ods.ods_dms_uc_uc_assessment_info;
create table if not exists ods.ods_dms_uc_uc_assessment_info(
id string comment '主键'
,ass_serial bigint comment '评估编号'
,dealer_code string comment '销售店代码'
,vehicle_manage_no string comment '车辆管理编号'
,negotiation_id string comment '商谈ID'
,sq bigint comment '序列号'
,ass_status string comment '评估状态'
,branch_code string comment '店铺代码'
,vinno string comment '车架号'
,ass_date string comment '评估日期'
,appraiser_memo string comment '评估师寄语'
,appraiser_account string comment '评估师账号'
,appraiser_name string comment '评估师名称'
,check_manage_no string comment '检查管理No'
,vehicle_config_info_json string comment '车辆配置信息Json'
,vehicle_check_remark_json string comment '车辆检查备注Json'
,vhcl_check_remark_label_json string comment '车辆检查备注标签Json'
,vehicle_addi_check_json string comment '车辆额外检查Json'
,vehicle_img_json string comment '车辆图片Json'
,vehicle_defect_info_json string comment '车辆缺陷信息Json'
,imp_service_info_json string comment '重要维修保养信息Json'
,update_account string comment '更新账号'
,del_flag bigint comment '删除标识'
,create_by bigint comment '创建者'
,create_time string comment '创建时间'
,update_by bigint comment '更新者'
,update_time string comment '更新时间'
,remark string comment '备注'
,version bigint comment '版本号'
,dl_batch_id string comment 'dl加载批次'
,extract_time string comment '抽取表时的系统时间（以北京时间为标准时区时间）'
,load_time string comment '数据加载到hive的时间'
,source_system string comment '来源系统'
,insert_time string comment '数据写入时间'
,biz_date string comment '分区字段'
) comment '评估单'
stored as parquet
tblproperties("parquet.compress"="snappy");



drop table if exists ods.ods_dms_uc_uc_assessment_ledger;
create table if not exists ods.ods_dms_uc_uc_assessment_ledger(
id string comment '主键'
,vehicle_manage_no string comment '车辆管理编号'
,dealer_code string comment '销售店代码'
,branch_code string comment '店铺代码'
,dealer_name string comment '销售店名称'
,ass_status string comment '评估状态'
,vinno string comment '车架号'
,engine_number string comment '发动机号'
,license_plate_number string comment '车牌号'
,negotiation_id string comment '商谈ID'
,customer_id string comment '客户ID'
,customer_name string comment '客户姓名'
,mobile_phone string comment '手机号'
,telephone_number string comment '电话号码'
,brand_code string comment '品牌CD'
,brand_name string comment '品牌名称'
,maker_code string comment '厂商代码'
,maker_name string comment '厂商名称'
,vehicle_model_code string comment '车型代码'
,vehicle_model_name string comment '车型名称'
,vehicle_grade string comment '车辆等级'
,first_regist_date string comment '首次注册日期'
,odometer bigint comment '行驶里程'
,exhaust string comment '排量'
,fuel_type_code string comment '燃料种类代码'
,fuel_type_name string comment '燃料种类名称'
,vehicle_type_code string comment '车辆类型代码'
,vehicle_category_name string comment '车辆类型名称'
,gearbox_type string comment '变速箱类型'
,gearbox_name string comment '变速箱名称'
,gearbox_category string comment '变速箱分类'
,gearbox_category_name string comment '变速箱分类名称'
,exterior_color_code_1 string comment '外装色CD1'
,exterior_color_1 string comment '外装色1'
,exterior_color_code_2 string comment '外装色CD2'
,exterior_color_2 string comment '外装色2'
,cover_thumbnail_img_url string comment '封面缩略图片URL'
,ass_serial bigint comment '评估编号'
,ass_date string comment '评估日期'
,ass_count bigint comment '评估次数'
,appraiser_memo string comment '评估师寄语'
,related_type string comment '关联类型'
,related_id string comment '关联ID'
,sales_decision_time string comment '销售决策时间'
,sales_decision_status string comment '销售决策状态'
,plan_sales_method string comment '计划销售方式'
,retail_ref_sales_price decimal(12,2) comment '零售参考销售价格'
,retail_plan_sales_price decimal(12,2) comment '零售计划销售价格'
,retail_ref_purchase_price decimal(12,2) comment '零售参考采购价格'
,retail_plan_purchase_price decimal(12,2) comment '零售计划采购价格'
,retail_bench_gross_profit decimal(12,2) comment '零售基准毛利'
,retail_plan_gross_profit decimal(12,2) comment '零售计划毛利'
,whsle_ref_sales_price decimal(12,2) comment '批售参考销售价格'
,whsle_plan_sales_price decimal(12,2) comment '批售计划销售价格'
,whsle_ref_purchase_price decimal(12,2) comment '批售参考采购价格'
,whsle_plan_purchase_price decimal(12,2) comment '批售计划采购价格'
,whsle_bench_gross_profit decimal(12,2) comment '批售基准毛利'
,whsle_plan_gross_profit decimal(12,2) comment '批售计划毛利'
,new_vehicle_guide_price decimal(12,2) comment '新车指导价格'
,del_flag bigint comment '删除标识'
,create_by bigint comment '创建者'
,create_time string comment '创建时间'
,update_by bigint comment '更新者'
,update_time string comment '更新时间'
,remark string comment '备注'
,version bigint comment '版本号'
,dl_batch_id string comment 'dl加载批次'
,extract_time string comment '抽取表时的系统时间（以北京时间为标准时区时间）'
,load_time string comment '数据加载到hive的时间'
,source_system string comment '来源系统'
,insert_time string comment '数据写入时间'
,biz_date string comment '分区字段'
) comment '二手车评估台账'
stored as parquet
tblproperties("parquet.compress"="snappy");



drop table if exists ods.ods_dms_uc_uc_assessment_vehicle_info;
create table if not exists ods.ods_dms_uc_uc_assessment_vehicle_info(
id string comment '主键'
,ass_serial bigint comment '评估编号'
,dealer_code string comment '销售店代码'
,vehicle_manage_no string comment '车辆管理编号'
,branch_code string comment '店铺代码'
,brand_code string comment '品牌CD'
,brand_name string comment '品牌名称'
,maker_code string comment '厂商代码'
,maker_name string comment '厂商名称'
,vehicle_model_code string comment '车型代码'
,vehicle_model_name string comment '车型名称'
,vehicle_grade string comment '车辆等级'
,vehicle_type_code string comment '车辆类型代码'
,vehicle_category_name string comment '车辆类型名称'
,national_standard_code string comment '国标代码'
,vinno string comment '车架号'
,engine_number string comment '发动机号'
,license_plate_number string comment '车牌号'
,production_date string comment '制造日期'
,exterior_color_code_1 string comment '外装色CD1'
,exterior_color_1 string comment '外装色1'
,exterior_color_code_2 string comment '外装色CD2'
,exterior_color_2 string comment '外装色2'
,color_change_diff string comment '颜色变更区分'
,interior_color_code_1 string comment '内装色CD1'
,interior_color_1 string comment '内装色1'
,interior_color_code_2 string comment '内装色CD2'
,interior_color_2 string comment '内装色2'
,odometer bigint comment '行驶里程'
,first_regist_date string comment '首次注册日期'
,recent_regist_date string comment '最近注册日期'
,use_nature string comment '使用性质'
,whole_quality_level string comment '整体品质级别'
,elect_level string comment '机电级别'
,outside_rating string comment '外观定级'
,interior_level string comment '内饰级别'
,accident_level string comment '事故级别'
,collision_accident_diff string comment '碰撞事故区分'
,water_accident_diff string comment '水浸事故区分'
,fire_accident_diff string comment '火烧事故区分'
,excessive_modified_diff string comment '过度改装区分'
,wty_type string comment '三包类型'
,instrument_tampering_flag string comment '仪表篡改标识'
,vehicle_door_qty bigint comment '车门数量'
,rate_allow_people_qty bigint comment '额定载客人数'
,whole_weight decimal(9,3) comment '整备质量'
,car_length string comment '车长'
,car_width string comment '车宽'
,car_height string comment '车高'
,fuel_type_code string comment '燃料种类代码'
,fuel_type_name string comment '燃料种类名称'
,exhaust string comment '排量'
,fuel_consumption string comment '油耗'
,discharge_standard string comment '排放标准'
,gearbox_type string comment '变速箱类型'
,gearbox_name string comment '变速箱名称'
,drive_method_serial string comment '驱动方式编号'
,drive_method_name string comment '驱动方式名称'
,cover_thumbnail_img_url string comment '封面缩略图片URL'
,del_flag bigint comment '删除标识'
,create_by bigint comment '创建者'
,create_time string comment '创建时间'
,update_by bigint comment '更新者'
,update_time string comment '更新时间'
,remark string comment '备注'
,version bigint comment '版本号'
,dl_batch_id string comment 'dl加载批次'
,extract_time string comment '抽取表时的系统时间（以北京时间为标准时区时间）'
,load_time string comment '数据加载到hive的时间'
,source_system string comment '来源系统'
,insert_time string comment '数据写入时间'
,biz_date string comment '分区字段'
) comment '评估车辆基本信息'
stored as parquet
tblproperties("parquet.compress"="snappy");



drop table if exists ods.ods_dms_uc_uc_assessment_vehicle_info_2;
create table if not exists ods.ods_dms_uc_uc_assessment_vehicle_info_2(
id string comment '主键'
,ass_serial bigint comment '评估编号'
,dealer_code string comment '销售店代码'
,vehicle_manage_no string comment '车辆管理编号'
,branch_code string comment '店铺代码'
,vehicle_check_eff_period string comment '车辆年审期限'
,comp_ins_period string comment '交强险期限'
,vehicle_tax_period string comment '车船税期限'
,business_ins_eff_period string comment '商业保险有效期限'
,vehicle_tools string comment '车载工具'
,vehicle_use_manual string comment '车辆使用手册'
,vehicle_service_manual string comment '车辆维修保养手册'
,del_flag bigint comment '删除标识'
,create_by bigint comment '创建者'
,create_time string comment '创建时间'
,update_by bigint comment '更新者'
,update_time string comment '更新时间'
,remark string comment '备注'
,version bigint comment '版本号'
,dl_batch_id string comment 'dl加载批次'
,extract_time string comment '抽取表时的系统时间（以北京时间为标准时区时间）'
,load_time string comment '数据加载到hive的时间'
,source_system string comment '来源系统'
,insert_time string comment '数据写入时间'
,biz_date string comment '分区字段'
) comment '评估车辆基本信息2'
stored as parquet
tblproperties("parquet.compress"="snappy");



drop table if exists ods.ods_dms_uc_uc_assessment_vehicle_info_3;
create table if not exists ods.ods_dms_uc_uc_assessment_vehicle_info_3(
id string comment '主键'
,ass_serial bigint comment '评估编号'
,dealer_code string comment '销售店代码'
,vehicle_manage_no string comment '车辆管理编号'
,branch_code string comment '店铺代码'
,service_count bigint comment '维修保养次数'
,recent_service_date string comment '最近维修保养日期'
,recent_service_mileage bigint comment '最近维修保养里程'
,recent_service_dealer string comment '最近维修保养销售店'
,service_history_flag string comment '维修保养履历标识'
,maintain_suggest_result string comment '维修建议与结果'
,del_flag bigint comment '删除标识'
,create_by bigint comment '创建者'
,create_time string comment '创建时间'
,update_by bigint comment '更新者'
,update_time string comment '更新时间'
,remark string comment '备注'
,version bigint comment '版本号'
,dl_batch_id string comment 'dl加载批次'
,extract_time string comment '抽取表时的系统时间（以北京时间为标准时区时间）'
,load_time string comment '数据加载到hive的时间'
,source_system string comment '来源系统'
,insert_time string comment '数据写入时间'
,biz_date string comment '分区字段'
) comment '评估车辆基本信息3'
stored as parquet
tblproperties("parquet.compress"="snappy");



drop table if exists ods.ods_dms_uc_uc_authen_apply;
create table if not exists ods.ods_dms_uc_uc_authen_apply(
id string comment '主键'
,dealer_code string comment '销售店代码'
,branch_code string comment '店铺代码'
,vehicle_manage_no string comment '车辆管理编号'
,auth_apply_no string comment '认证申请编号'
,first_regist_date string comment '首次注册日期'
,vinno string comment '车架号'
,uc_auth_no string comment '二手车认证编号'
,authen_type string comment '认证类型'
,other_dealer_authen_flag string comment '其他销售店认证标识'
,authen_apply_type_code string comment '认证申请类型CD'
,auth_status string comment '认证状态'
,cancel_reason_type string comment '取消原因类型'
,auth_apply_time string comment '认证申请时间'
,authen_apply_staff_account string comment '认证申请担当账号'
,authen_apply_staff_name string comment '认证申请担当姓名'
,authen_operate_time string comment '认证操作时间'
,authen_operate_account string comment '认证操作账号'
,authen_operate_staff_name string comment '认证操作担当姓名'
,authen_operate_opinion string comment '认证操作意见'
,uc_auth_time string comment '二手车认证生效时间'
,uc_auth_due_date string comment '二手车认证到期日'
,del_flag bigint comment '删除标识'
,create_by bigint comment '创建者'
,create_time string comment '创建时间'
,update_by bigint comment '更新者'
,update_time string comment '更新时间'
,remark string comment '备注'
,version bigint comment '版本号'
,dl_batch_id string comment 'dl加载批次'
,extract_time string comment '抽取表时的系统时间（以北京时间为标准时区时间）'
,load_time string comment '数据加载到hive的时间'
,source_system string comment '来源系统'
,insert_time string comment '数据写入时间'
,biz_date string comment '分区字段'
) comment '认证申请'
stored as parquet
tblproperties("parquet.compress"="snappy");



drop table if exists ods.ods_dms_uc_uc_cust_car_buy_follow;
create table if not exists ods.ods_dms_uc_uc_cust_car_buy_follow(
id string comment '主键'
,dealer_code string comment '销售店代码'
,branch_code string comment '店铺代码'
,negotiation_id string comment '商谈ID'
,follow_time string comment '跟进时间'
,car_buy_follow_status string comment '买车跟进状态'
,follow_account string comment '跟进账号'
,follow_staff_name string comment '跟进担当姓名'
,car_buy_follow_result string comment '买车跟进结果'
,continue_reason_type string comment '继续原因类型'
,abandon_reason_type string comment '放弃原因类型'
,vehicle_manage_no string comment '车辆管理编号'
,contact_diff string comment '联系区分'
,contact_content_code string comment '联系内容代码'
,customer_expect_price decimal(12,2) comment '客户期望价格'
,prompt_price decimal(12,2) comment '提示价格'
,intn_level string comment '意向级别'
,plan_follow_time string comment '计划跟进时间'
,plan_follow_content_diff string comment '计划跟进内容区分'
,del_flag bigint comment '删除标识'
,create_by bigint comment '创建者'
,create_time string comment '创建时间'
,update_by bigint comment '更新者'
,update_time string comment '更新时间'
,remark string comment '备注'
,version bigint comment '版本号'
,dl_batch_id string comment 'dl加载批次'
,extract_time string comment '抽取表时的系统时间（以北京时间为标准时区时间）'
,load_time string comment '数据加载到hive的时间'
,source_system string comment '来源系统'
,insert_time string comment '数据写入时间'
,biz_date string comment '分区字段'
) comment '客户买车跟进'
stored as parquet
tblproperties("parquet.compress"="snappy");



drop table if exists ods.ods_dms_uc_uc_cust_car_sale_follow;
create table if not exists ods.ods_dms_uc_uc_cust_car_sale_follow(
id string comment '主键'
,dealer_code string comment '销售店代码'
,branch_code string comment '店铺代码'
,negotiation_id string comment '商谈ID'
,follow_time string comment '跟进时间'
,car_sale_follow_status string comment '卖车跟进状态'
,follow_account string comment '跟进账号'
,follow_staff_name string comment '跟进担当姓名'
,car_sale_follow_result string comment '卖车跟进结果'
,continue_reason_type string comment '继续原因类型'
,abandon_reason_type string comment '放弃原因类型'
,vehicle_manage_no string comment '车辆管理编号'
,contact_diff string comment '联系区分'
,contact_content_code string comment '联系内容代码'
,customer_expect_price decimal(12,2) comment '客户期望价格'
,prompt_price decimal(12,2) comment '提示价格'
,intn_level string comment '意向级别'
,plan_follow_time string comment '计划跟进时间'
,plan_follow_content_diff string comment '计划跟进内容区分'
,del_flag bigint comment '删除标识'
,create_by bigint comment '创建者'
,create_time string comment '创建时间'
,update_by bigint comment '更新者'
,update_time string comment '更新时间'
,remark string comment '备注'
,version bigint comment '版本号'
,dl_batch_id string comment 'dl加载批次'
,extract_time string comment '抽取表时的系统时间（以北京时间为标准时区时间）'
,load_time string comment '数据加载到hive的时间'
,source_system string comment '来源系统'
,insert_time string comment '数据写入时间'
,biz_date string comment '分区字段'
) comment '客户卖车跟进'
stored as parquet
tblproperties("parquet.compress"="snappy");



drop table if exists ods.ods_dms_uc_uc_cust_sales_vio_settl;
create table if not exists ods.ods_dms_uc_uc_cust_sales_vio_settl(
id string comment '主键'
,buyer_sales_violation_serial bigint comment '买方销售违约编号'
,dealer_code string comment '销售店代码'
,branch_code string comment '店铺代码'
,vehicle_manage_no string comment '车辆管理编号'
,vinno string comment '车架号'
,sales_contract_serial string comment '销售合同编号'
,violation_amount decimal(12,2) comment '违约金额'
,settl_status string comment '结算状态'
,finish_payment_time string comment '完成付款时间'
,input_date string comment '录入日期'
,del_flag bigint comment '删除标识'
,create_by bigint comment '创建者'
,create_time string comment '创建时间'
,update_by bigint comment '更新者'
,update_time string comment '更新时间'
,remark string comment '备注'
,version bigint comment '版本号'
,dl_batch_id string comment 'dl加载批次'
,extract_time string comment '抽取表时的系统时间（以北京时间为标准时区时间）'
,load_time string comment '数据加载到hive的时间'
,source_system string comment '来源系统'
,insert_time string comment '数据写入时间'
,biz_date string comment '分区字段'
) comment '客端销售违约结算单'
stored as parquet
tblproperties("parquet.compress"="snappy");



drop table if exists ods.ods_dms_uc_uc_customer_info;
create table if not exists ods.ods_dms_uc_uc_customer_info(
id string comment '主键'
,dealer_code string comment '销售店代码'
,branch_code string comment '店铺代码'
,customer_id string comment '客户ID'
,customer_name string comment '客户姓名'
,negotiation_customer_address string comment '商谈客户地址'
,customer_mobile_phone string comment '客户移动电话'
,customer_fixed_tel string comment '客户固定电话'
,customer_postal_code string comment '客户邮编'
,customer_email string comment '客户电子邮箱'
,comm_activity_type string comment '商业性活动类型'
,del_flag bigint comment '删除标识'
,create_by bigint comment '创建者'
,create_time string comment '创建时间'
,update_by bigint comment '更新者'
,update_time string comment '更新时间'
,remark string comment '备注'
,version bigint comment '版本号'
,dl_batch_id string comment 'dl加载批次'
,extract_time string comment '抽取表时的系统时间（以北京时间为标准时区时间）'
,load_time string comment '数据加载到hive的时间'
,source_system string comment '来源系统'
,insert_time string comment '数据写入时间'
,biz_date string comment '分区字段'
) comment '二手车客户'
stored as parquet
tblproperties("parquet.compress"="snappy");



drop table if exists ods.ods_dms_uc_uc_demand_info;
create table if not exists ods.ods_dms_uc_uc_demand_info(
id string comment '主键'
,dealer_code string comment '销售店代码'
,branch_code string comment '店铺代码'
,uc_req_id string comment '二手车需求ID'
,uc_clue_id string comment '二手车线索ID'
,uc_req_status string comment '二手车需求状态'
,business_diff string comment '业务区分'
,sold_vehicle_model_name string comment '售出车型名称'
,icm_sold_vehicle_info_json string comment 'ICM售出车辆信息Json'
,d2c_sold_vehicle_info_json string comment 'D2C售出车辆信息Json'
,car_buy_intn_type string comment '购车意向类型'
,intn_new_vehicle_info_json string comment '意向新车信息Json'
,intn_uc_type string comment '意向二手车类型'
,intn_vehicle_manage_no string comment '意向车辆管理编号'
,intn_uc_cond_json string comment '意向二手车条件Json'
,purchase_type string comment '购买类型'
,del_flag bigint comment '删除标识'
,create_by bigint comment '创建者'
,create_time string comment '创建时间'
,update_by bigint comment '更新者'
,update_time string comment '更新时间'
,remark string comment '备注'
,version bigint comment '版本号'
,dl_batch_id string comment 'dl加载批次'
,extract_time string comment '抽取表时的系统时间（以北京时间为标准时区时间）'
,load_time string comment '数据加载到hive的时间'
,source_system string comment '来源系统'
,insert_time string comment '数据写入时间'
,biz_date string comment '分区字段'
) comment '二手车需求'
stored as parquet
tblproperties("parquet.compress"="snappy");



drop table if exists ods.ods_dms_uc_uc_dlr_sales_vio_settl;
create table if not exists ods.ods_dms_uc_uc_dlr_sales_vio_settl(
id string comment '主键'
,seller_sales_violation_serial bigint comment '买方销售违约编号'
,dealer_code string comment '销售店代码'
,branch_code string comment '店铺代码'
,vehicle_manage_no string comment '车辆管理编号'
,vinno string comment '车架号'
,sales_contract_serial string comment '销售合同编号'
,violation_amount decimal(12,2) comment '违约金额'
,settl_status string comment '结算状态'
,finish_payment_time string comment '完成付款时间'
,input_date string comment '录入日期'
,del_flag bigint comment '删除标识'
,create_by bigint comment '创建者'
,create_time string comment '创建时间'
,update_by bigint comment '更新者'
,update_time string comment '更新时间'
,remark string comment '备注'
,version bigint comment '版本号'
,dl_batch_id string comment 'dl加载批次'
,extract_time string comment '抽取表时的系统时间（以北京时间为标准时区时间）'
,load_time string comment '数据加载到hive的时间'
,source_system string comment '来源系统'
,insert_time string comment '数据写入时间'
,biz_date string comment '分区字段'
) comment '店端销售违约结算单'
stored as parquet
tblproperties("parquet.compress"="snappy");



drop table if exists ods.ods_dms_uc_uc_exchange_vehicle_relation;
create table if not exists ods.ods_dms_uc_uc_exchange_vehicle_relation(
id string comment '主键'
,displace_vehicle_related_id string comment '置换车辆关联ID'
,dealer_code string comment '销售店代码'
,branch_code string comment '店铺代码'
,vehicle_manage_no string comment '车辆管理编号'
,vinno string comment '车架号'
,car_owner_name string comment '车主名称'
,displace_vehicle_manage_no string comment '置换车辆管理编号'
,displace_vinno string comment '置换车架号'
,displace_vehicle_picture_url string comment '置换车辆图片路径'
,displace_vehicle_config_grade string comment '置换车辆配置等级'
,displace_vehicle_model_code string comment '置换车型代码'
,displace_vehicle_model_name string comment '置换车型名字'
,displace_vehicle_nominee_name string comment '置换车辆名义人姓名'
,displace_vehicle_nominee_tel string comment '置换车辆名义人电话'
,displace_vehicle_sales_date string comment '置换车辆销售日期'
,displace_related_status bigint comment '置换关联状态'
,displace_related_time string comment '置换关联时间'
,displace_type string comment '置换类型'
,displace_vehicle_related_type string comment '置换车辆关联类型'
,del_flag bigint comment '删除标识'
,create_by bigint comment '创建者'
,create_time string comment '创建时间'
,update_by bigint comment '更新者'
,update_time string comment '更新时间'
,remark string comment '备注'
,version bigint comment '版本号'
,dl_batch_id string comment 'dl加载批次'
,extract_time string comment '抽取表时的系统时间（以北京时间为标准时区时间）'
,load_time string comment '数据加载到hive的时间'
,source_system string comment '来源系统'
,insert_time string comment '数据写入时间'
,biz_date string comment '分区字段'
) comment '置换车辆关联单'
stored as parquet
tblproperties("parquet.compress"="snappy");



drop table if exists ods.ods_dms_uc_uc_inventory_ledger;
create table if not exists ods.ods_dms_uc_uc_inventory_ledger(
id string comment '主键'
,vehicle_manage_no string comment '车辆管理编号'
,dealer_code string comment '销售店代码'
,branch_code string comment '店铺代码'
,dealer_name string comment '销售店名称'
,uc_stock_status string comment '二手车库存状态'
,vinno string comment '车架号'
,engine_number string comment '发动机号'
,license_plate_number string comment '车牌号'
,mobile_phone string comment '手机号'
,telephone_number string comment '电话号码'
,customer_name string comment '客户姓名'
,brand_code string comment '品牌CD'
,brand_name string comment '品牌名称'
,maker_code string comment '厂商代码'
,maker_name string comment '厂商名称'
,vehicle_model_code string comment '车型代码'
,vehicle_model_name string comment '车型名称'
,config_grade string comment '配置等级'
,first_regist_date string comment '首次注册日期'
,production_date string comment '制造日期'
,odometer bigint comment '行驶里程'
,exhaust string comment '排量'
,fuel_type_code string comment '燃料种类代码'
,fuel_type_name string comment '燃料种类名称'
,vehicle_type_code string comment '车辆类型代码'
,vehicle_category_name string comment '车辆类型名称'
,gearbox_type string comment '变速箱类型'
,gearbox_name string comment '变速箱名称'
,gearbox_category string comment '变速箱分类'
,gearbox_category_name string comment '变速箱分类名称'
,exterior_color_code_1 string comment '外装色CD1'
,exterior_color_1 string comment '外装色1'
,exterior_color_code_2 string comment '外装色CD2'
,exterior_color_2 string comment '外装色2'
,ass_date string comment '评估日期'
,detect_work_order_finish_date string comment '检测工单完成日期'
,sales_decision_time string comment '销售决策时间'
,ref_sales_price decimal(12,2) comment '参考销售价格'
,plan_sales_price decimal(12,2) comment '计划销售价格'
,ref_purchase_price decimal(12,2) comment '参考采购价格'
,plan_purchase_price decimal(12,2) comment '计划采购价格'
,sign_type bigint comment '签约类型'
,sign_time string comment '签约时间'
,cons_contract_serial string comment '寄售协议编号'
,cons_contract_status string comment '寄售协议状态'
,cons_start_date string comment '寄售开始日期'
,cons_end_date string comment '寄售结束日期'
,cons_expect_price decimal(12,0) comment '寄售期望价格'
,cons_type_code string comment '寄售类型代码'
,cons_service_cost decimal(12,0) comment '寄售服务费用'
,purchase_contract_id string comment '采购协议ID'
,purchase_contract_status bigint comment '采购协议状态'
,purchase_sign_date string comment '采购签约日期'
,purchase_cancel_date string comment '采购取消日期'
,purchase_price decimal(12,2) comment '采购价格'
,car_owner_name string comment '车主名称'
,car_owner_id_card string comment '车主身份证号码'
,car_owner_mobile_phone string comment '车主电话'
,car_owner_fixed_tel string comment '车主固定电话'
,sales_method string comment '销售方式'
,storage_method bigint comment '入库方式'
,storage_type string comment '入库类型'
,elect_defect_flag string comment '机电缺陷标识'
,vehicle_place_address string comment '车辆放置地址'
,related_type string comment '关联类型'
,related_id string comment '关联ID'
,plan_storage_date string comment '计划入库日期'
,actual_storage_date string comment '实际入库日期'
,transfer_flag string comment '过户标识'
,plan_transfer_date string comment '计划过户日期'
,actual_transfer_date string comment '实际过户日期'
,delivery_finish_date string comment '交车完成日期'
,dealer_pay_transfer_cost decimal(12,2) comment '销售店承担过户费用'
,dealer_new_car_owner_name string comment '销售店新车主姓名'
,dealer_new_car_owner_id_card string comment '销售店新车主身份证号码'
,dlr_new_car_owner_mobile_phone string comment '销售店新车主手机号'
,dealer_new_car_owner_address string comment '销售店新车主地址'
,dlr_new_car_owner_lpn string comment '销售店新车主车牌号'
,displace_related_operate_flag bigint comment '置换关联操作标识'
,del_flag bigint comment '删除标识'
,create_by bigint comment '创建者'
,create_time string comment '创建时间'
,update_by bigint comment '更新者'
,update_time string comment '更新时间'
,remark string comment '备注'
,version bigint comment '版本号'
,dl_batch_id string comment 'dl加载批次'
,extract_time string comment '抽取表时的系统时间（以北京时间为标准时区时间）'
,load_time string comment '数据加载到hive的时间'
,source_system string comment '来源系统'
,insert_time string comment '数据写入时间'
,biz_date string comment '分区字段'
) comment '二手车库存台账'
stored as parquet
tblproperties("parquet.compress"="snappy");



drop table if exists ods.ods_dms_uc_uc_inventory_ledger_transfer;
create table if not exists ods.ods_dms_uc_uc_inventory_ledger_transfer(
id string comment '主键'
,dealer_code string comment '销售店代码'
,branch_code string comment '店铺代码'
,vehicle_manage_no string comment '车辆管理编号'
,plan_transfer_date string comment '计划过户日期'
,actual_transfer_date string comment '实际过户日期'
,dealer_pay_transfer_cost decimal(12,2) comment '销售店承担过户费用'
,dealer_new_car_owner_name string comment '销售店新车主姓名'
,dealer_new_car_owner_id_card string comment '销售店新车主身份证号码'
,dlr_new_car_owner_mobile_phone string comment '销售店新车主手机号'
,dealer_new_car_owner_address string comment '销售店新车主地址'
,dlr_new_car_owner_lpn string comment '销售店新车主车牌号'
,cancel_time string comment '取消时间'
,del_flag bigint comment '删除标识'
,create_by bigint comment '创建者'
,create_time string comment '创建时间'
,update_by bigint comment '更新者'
,update_time string comment '更新时间'
,remark string comment '备注'
,version bigint comment '版本号'
,dl_batch_id string comment 'dl加载批次'
,extract_time string comment '抽取表时的系统时间（以北京时间为标准时区时间）'
,load_time string comment '数据加载到hive的时间'
,source_system string comment '来源系统'
,insert_time string comment '数据写入时间'
,biz_date string comment '分区字段'
) comment '二手车库存台账过户信息'
stored as parquet
tblproperties("parquet.compress"="snappy");



drop table if exists ods.ods_dms_uc_uc_mst_dealer;
create table if not exists ods.ods_dms_uc_uc_mst_dealer(
id string comment '主键'
,dealer_code string comment '销售店代码'
,branch_code string comment '店铺代码'
,dealer_name string comment '销售店名称'
,dealer_region string comment '销售店区域'
,dealer_address string comment '销售店地址'
,dealer_contact_tel string comment '销售店联系电话'
,dealer_website string comment '销售店主页'
,dealer_picture_url string comment '销售店图片'
,dealer_fax string comment '销售店传真'
,uc_dept_staff_telephone string comment '二手车部担当电话'
,business_start_time string comment '营业开始时间'
,business_end_time string comment '营业结束时间'
,dealer_theme_slogan string comment '店的主题口号'
,map_img string comment '地图图片'
,region_code string comment '区域代码'
,region_name string comment '区域名称'
,province_code string comment '省代码'
,province_name string comment '省份名称'
,city_code string comment '市代码'
,city_name string comment '市名称'
,ass_hotline string comment '评估热线'
,sales_hotline string comment '销售热线'
,dlr_image_display string comment '销售店显示图片'
,dealer_thumbnail_img string comment '销售店缩略图片'
,map_display_img string comment '地图显示图片'
,map_thumbnail_img string comment '地图缩略图片'
,contacts_account string comment '联系人账号'
,dealer_prefix string comment '销售店前缀'
,shop_enter_flag string comment '商城入驻标识'
,displace_cert_flag string comment '置换资格标识'
,displace_cert_effective_date string comment '置换资格生效日期'
,displace_cert_effective_flag string comment '置换资格生效标识'
,retail_cert_flag string comment '零售资格标识'
,retail_cert_effective_date string comment '零售资格生效日期'
,retail_cert_effective_flag string comment '零售资格生效标识'
,after_sales_service_flag string comment '售后服务标识'
,authen_service_flag string comment '认证服务标识'
,authen_service_contact_account string comment '认证服务联系账号'
,authen_service_contact_name string comment '认证服务联系姓名'
,authen_service_contact_telephone string comment '认证服务联系电话'
,authen_service_cost decimal(12,2) comment '认证服务费用'
,maker_suggest_service_cost decimal(12,2) comment '厂商建议服务费用'
,authen_service_remark string comment '认证服务备注'
,del_flag bigint comment '删除标识'
,create_by bigint comment '创建者'
,create_time string comment '创建时间'
,update_by bigint comment '更新者'
,update_time string comment '更新时间'
,remark string comment '备注'
,version bigint comment '版本号'
,dl_batch_id string comment 'dl加载批次'
,extract_time string comment '抽取表时的系统时间（以北京时间为标准时区时间）'
,load_time string comment '数据加载到hive的时间'
,source_system string comment '来源系统'
,insert_time string comment '数据写入时间'
,biz_date string comment '分区字段'
) comment '销售店信息'
stored as parquet
tblproperties("parquet.compress"="snappy");



drop table if exists ods.ods_dms_uc_uc_mst_elect_defect;
create table if not exists ods.ods_dms_uc_uc_mst_elect_defect(
id string comment '主键'
,detect_position_type string comment '检测部位类型'
,detect_position_group_code string comment '检测部位组代码'
,detect_position_code string comment '检测部位代码'
,sort bigint comment '排序'
,defect_item_name string comment '缺陷项名称'
,defect_item_name_local string comment '缺陷项名称本地'
,defect_item_name_2 string comment '缺陷项名称2'
,defect_item_name_2_local string comment '缺陷项名称2本地'
,del_flag bigint comment '删除标识'
,create_by bigint comment '创建者'
,create_time string comment '创建时间'
,update_by bigint comment '更新者'
,update_time string comment '更新时间'
,remark string comment '备注'
,version bigint comment '版本号'
,dl_batch_id string comment 'dl加载批次'
,extract_time string comment '抽取表时的系统时间（以北京时间为标准时区时间）'
,load_time string comment '数据加载到hive的时间'
,source_system string comment '来源系统'
,insert_time string comment '数据写入时间'
,biz_date string comment '分区字段'
) comment '机电缺陷'
stored as parquet
tblproperties("parquet.compress"="snappy");



drop table if exists ods.ods_dms_uc_uc_negotiation;
create table if not exists ods.ods_dms_uc_uc_negotiation(
id string comment '主键'
,dealer_code string comment '销售店代码'
,branch_code string comment '店铺代码'
,negotiation_id string comment '商谈ID'
,customer_id string comment '客户ID'
,customer_name string comment '客户姓名'
,negotiation_customer_address string comment '商谈客户地址'
,customer_mobile_phone string comment '客户移动电话'
,customer_fixed_tel string comment '客户固定电话'
,customer_postal_code string comment '客户邮编'
,activity_manager_account string comment '活动管理者账号'
,activity_manager_name string comment '活动管理者姓名'
,source_code string comment '来源代码'
,source_name string comment '来源名称'
,source_first_level_code string comment '一级来源代码'
,source_first_level_name string comment '一级来源名称'
,source_second_level_code string comment '二级来源代码'
,source_second_level_name string comment '二级来源名称'
,introducer_dept_code string comment '介绍人部门代码'
,introducer_dept_name string comment '介绍人部门名称'
,introducer_account string comment '介绍人账号'
,introducer_name string comment '介绍人姓名'
,intn_level string comment '意向级别'
,negotiation_status string comment '商谈状态'
,manager_dist_flag string comment '管理者分配标识'
,uc_req_id string comment '二手车需求ID'
,uc_clue_id string comment '二手车线索ID'
,clue_create_time string comment '线索创建时间'
,follow_account string comment '跟进账号'
,follow_staff_name string comment '跟进担当姓名'
,follow_time string comment '跟进时间'
,next_follow_time string comment '下次跟进时间'
,business_diff string comment '业务区分'
,intn_type string comment '意向类型'
,vehicle_manage_no string comment '车辆管理编号'
,cover_thumbnail_img_url string comment '封面缩略图片URL'
,brand_code string comment '品牌CD'
,brand_name string comment '品牌名称'
,maker_code string comment '厂商代码'
,maker_name string comment '厂商名称'
,vehicle_model_code string comment '车型代码'
,vehicle_model_name string comment '车型名称'
,vehicle_grade string comment '车辆等级'
,license_plate_number string comment '车牌号'
,vinno string comment '车架号'
,first_regist_date string comment '首次注册日期'
,ass_date string comment '评估日期'
,purchase_sign_date string comment '采购签约日期'
,cons_sign_date string comment '寄售签约日期'
,min_down_payment decimal(12,2) comment '最低首付'
,max_down_payment decimal(12,2) comment '最高首付'
,min_monthly_payment decimal(12,2) comment '最低月供'
,max_monthly_payment decimal(12,2) comment '最高月供'
,sales_sign_date string comment '销售签约日期'
,sales_negotiation_id string comment '销售商谈ID'
,del_flag bigint comment '删除标识'
,create_by bigint comment '创建者'
,create_time string comment '创建时间'
,update_by bigint comment '更新者'
,update_time string comment '更新时间'
,remark string comment '备注'
,version bigint comment '版本号'
,dl_batch_id string comment 'dl加载批次'
,extract_time string comment '抽取表时的系统时间（以北京时间为标准时区时间）'
,load_time string comment '数据加载到hive的时间'
,source_system string comment '来源系统'
,insert_time string comment '数据写入时间'
,biz_date string comment '分区字段'
) comment '二手车商谈'
stored as parquet
tblproperties("parquet.compress"="snappy");



drop table if exists ods.ods_dms_uc_uc_new_vhcl_exchange_achv;
create table if not exists ods.ods_dms_uc_uc_new_vhcl_exchange_achv(
id string comment '主键'
,new_vehicle_displace_achv_id string comment '新车置换业绩ID'
,dealer_code string comment '销售店代码'
,branch_code string comment '店铺代码'
,vehicle_manage_no string comment '车辆管理编号'
,vinno string comment '车架号'
,license_plate_number string comment '车牌号'
,achv_apply_status string comment '业绩申请状态'
,present_type string comment '赠品类型'
,displace_vehicle_related_id string comment '置换车辆关联ID'
,displace_vehicle_vinno string comment '置换车辆车架号'
,displace_vehicle_nominee_name string comment '置换车辆名义人姓名'
,displace_vehicle_nominee_tel string comment '置换车辆名义人电话'
,displace_vehicle_sales_date string comment '置换车辆销售日期'
,displace_vehicle_picture_url string comment '置换车辆图片路径'
,displace_vehicle_config_grade string comment '置换车辆配置等级'
,displace_vehicle_model_code string comment '置换车型代码'
,displace_vehicle_model_name string comment '置换车型名字'
,purchase_obtain_evidence_id string comment '采购取证ID'
,invoice_number string comment '发票号'
,invoice_amount decimal(10,2) comment '发票金额'
,actual_transfer_date string comment '实际过户日期'
,seller_name string comment '卖方姓名'
,seller_id_card string comment '卖方身份证'
,buyer_name string comment '买主名'
,buyer_id_card string comment '买方身份证'
,apply_time string comment '申请时间'
,apply_staff_account string comment '申请担当账号'
,apply_staff_name string comment '申请担当姓名'
,approve_time string comment '审批时间'
,approve_staff_account string comment '审核担当账号'
,approve_staff_name string comment '审核担当姓名'
,approve_opinion string comment '审批意见'
,cancel_time string comment '取消时间'
,cancel_staff_account string comment '取消担当账号'
,cancel_staff_name string comment '取消担当姓名'
,del_flag bigint comment '删除标识'
,create_by bigint comment '创建者'
,create_time string comment '创建时间'
,update_by bigint comment '更新者'
,update_time string comment '更新时间'
,remark string comment '备注'
,version bigint comment '版本号'
,dl_batch_id string comment 'dl加载批次'
,extract_time string comment '抽取表时的系统时间（以北京时间为标准时区时间）'
,load_time string comment '数据加载到hive的时间'
,source_system string comment '来源系统'
,insert_time string comment '数据写入时间'
,biz_date string comment '分区字段'
) comment '新车置换业绩单'
stored as parquet
tblproperties("parquet.compress"="snappy");



drop table if exists ods.ods_dms_uc_uc_purchase_contract_ledger;
create table if not exists ods.ods_dms_uc_uc_purchase_contract_ledger(
id string comment '主键'
,dealer_code string comment '销售店代码'
,branch_code string comment '店铺代码'
,vehicle_manage_no string comment '车辆管理编号'
,purchase_contract_id string comment '采购协议ID'
,vinno string comment '车架号'
,car_owner_type string comment '车主类型'
,car_owner_name string comment '车主名称'
,car_owner_id_card string comment '车主身份证号码'
,car_owner_mobile_phone string comment '车主电话'
,car_owner_tel string comment '车主固定电话'
,car_owner_zip string comment '车主邮编'
,car_owner_address string comment '车主住址'
,car_owner_email string comment '车主邮箱'
,license_plate_number string comment '车牌号'
,purchase_sign_date string comment '采购签约日期'
,purchase_cancel_date string comment '采购取消日期'
,cons_sign_date string comment '寄售签约日期'
,purchase_price decimal(12,2) comment '采购价格'
,plan_sales_method string comment '计划销售方式'
,whsle_target_code string comment '批售对象代码'
,whsle_target_type string comment '批售对象类型'
,plan_storage_date string comment '计划入库日期'
,plan_transfer_date string comment '计划过户日期'
,purchase_contract_status bigint comment '采购协议状态'
,del_flag bigint comment '删除标识'
,create_by bigint comment '创建者'
,create_time string comment '创建时间'
,update_by bigint comment '更新者'
,update_time string comment '更新时间'
,remark string comment '备注'
,version bigint comment '版本号'
,dl_batch_id string comment 'dl加载批次'
,extract_time string comment '抽取表时的系统时间（以北京时间为标准时区时间）'
,load_time string comment '数据加载到hive的时间'
,source_system string comment '来源系统'
,insert_time string comment '数据写入时间'
,biz_date string comment '分区字段'
) comment '采购协议台账'
stored as parquet
tblproperties("parquet.compress"="snappy");



drop table if exists ods.ods_dms_uc_uc_purchase_contract_other_cost;
create table if not exists ods.ods_dms_uc_uc_purchase_contract_other_cost(
id string comment '主键'
,purchase_other_cost_id string comment '采购其他费用ID'
,dealer_code string comment '销售店代码'
,branch_code string comment '店铺代码'
,vehicle_manage_no string comment '车辆管理编号'
,purchase_contract_id string comment '采购协议ID'
,cost_item_code string comment '费用项代码'
,cost_item_name string comment '费用项名称'
,cost_amount decimal(12,2) comment '费用金额'
,cost_input_date string comment '费用录入日期'
,del_flag bigint comment '删除标识'
,create_by bigint comment '创建者'
,create_time string comment '创建时间'
,update_by bigint comment '更新者'
,update_time string comment '更新时间'
,remark string comment '备注'
,version bigint comment '版本号'
,dl_batch_id string comment 'dl加载批次'
,extract_time string comment '抽取表时的系统时间（以北京时间为标准时区时间）'
,load_time string comment '数据加载到hive的时间'
,source_system string comment '来源系统'
,insert_time string comment '数据写入时间'
,biz_date string comment '分区字段'
) comment '销售成本'
stored as parquet
tblproperties("parquet.compress"="snappy");



drop table if exists ods.ods_dms_uc_uc_repair_authen_ledger;
create table if not exists ods.ods_dms_uc_uc_repair_authen_ledger(
id string comment '主键'
,repair_authen_id string comment '整备认证ID'
,dealer_code string comment '销售店代码'
,branch_code string comment '店铺代码'
,vehicle_manage_no string comment '车辆管理编号'
,vinno string comment '车架号'
,ledger_status string comment '台账状态'
,uc_auth_due_date string comment '二手车认证到期日'
,uc_auth_time string comment '二手车认证生效时间'
,authen_apply_type_code string comment '认证申请类型CD'
,authen_type string comment '认证类型'
,auth_apply_time string comment '认证申请时间'
,auth_apply_by_code string comment '认证申请人代码'
,uc_auth_no string comment '二手车认证编号'
,gtmc_vehicle_flag string comment '广汽丰田车辆标识'
,delivery_finish_date string comment '交车完成日期'
,sales_method string comment '销售方式'
,first_regist_date string comment '首次注册日期'
,ass_date string comment '评估日期'
,maker_code string comment '厂商代码'
,maker_name string comment '厂商名称'
,odometer bigint comment '行驶里程'
,vehicle_type_code string comment '车辆类型代码'
,vehicle_category_name string comment '车辆类型名称'
,vehicle_grade string comment '车辆等级'
,collision_accident_diff string comment '碰撞事故区分'
,water_accident_diff string comment '水浸事故区分'
,fire_accident_diff string comment '火烧事故区分'
,excessive_modified_diff string comment '过度改装区分'
,wty_type string comment '三包类型'
,instrument_tampering_flag string comment '仪表篡改标识'
,elect_level string comment '机电级别'
,accident_level string comment '事故级别'
,exhaust string comment '排量'
,del_flag bigint comment '删除标识'
,create_by bigint comment '创建者'
,create_time string comment '创建时间'
,update_by bigint comment '更新者'
,update_time string comment '更新时间'
,remark string comment '备注'
,version bigint comment '版本号'
,dl_batch_id string comment 'dl加载批次'
,extract_time string comment '抽取表时的系统时间（以北京时间为标准时区时间）'
,load_time string comment '数据加载到hive的时间'
,source_system string comment '来源系统'
,insert_time string comment '数据写入时间'
,biz_date string comment '分区字段'
) comment '整备认证台账'
stored as parquet
tblproperties("parquet.compress"="snappy");



drop table if exists ods.ods_dms_uc_uc_repair_cost;
create table if not exists ods.ods_dms_uc_uc_repair_cost(
id string comment '主键'
,dealer_code string comment '销售店代码'
,branch_code string comment '店铺代码'
,vehicle_manage_no string comment '车辆管理编号'
,vinno string comment '车架号'
,repair_id string comment '整备ID'
,repair_item_id string comment '整备项ID'
,project_source bigint comment '项目来源'
,repair_item_type string comment '整备项类型'
,repair_item_type_name string comment '整备项类型名称'
,repair_item_code string comment '整备项代码'
,repair_item_name string comment '整备项名称'
,repair_item_cost decimal(12,2) comment '整备项费用'
,del_flag bigint comment '删除标识'
,create_by bigint comment '创建者'
,create_time string comment '创建时间'
,update_by bigint comment '更新者'
,update_time string comment '更新时间'
,remark string comment '备注'
,version bigint comment '版本号'
,dl_batch_id string comment 'dl加载批次'
,extract_time string comment '抽取表时的系统时间（以北京时间为标准时区时间）'
,load_time string comment '数据加载到hive的时间'
,source_system string comment '来源系统'
,insert_time string comment '数据写入时间'
,biz_date string comment '分区字段'
) comment '整备费用'
stored as parquet
tblproperties("parquet.compress"="snappy");



drop table if exists ods.ods_dms_uc_uc_repair_item;
create table if not exists ods.ods_dms_uc_uc_repair_item(
id string comment '主键'
,repair_item_id string comment '整备项ID'
,dealer_code string comment '销售店代码'
,branch_code string comment '店铺代码'
,repair_item_code string comment '整备项代码'
,repair_item_name string comment '整备项名称'
,repair_item_type string comment '整备项类型'
,repair_item_type_name string comment '整备项类型名称'
,repair_item_cost decimal(12,2) comment '整备项费用'
,retail_bench_cost decimal(12,2) comment '零售基准费用'
,default_show_flag bigint comment '默认展示标识'
,brand_limit_diff bigint comment '品牌限定区分'
,default_choose_flag bigint comment '默认选择标识'
,sq bigint comment '序列号'
,repair_item_status string comment '整备项状态'
,del_flag bigint comment '删除标识'
,create_by bigint comment '创建者'
,create_time string comment '创建时间'
,update_by bigint comment '更新者'
,update_time string comment '更新时间'
,remark string comment '备注'
,version bigint comment '版本号'
,dl_batch_id string comment 'dl加载批次'
,extract_time string comment '抽取表时的系统时间（以北京时间为标准时区时间）'
,load_time string comment '数据加载到hive的时间'
,source_system string comment '来源系统'
,insert_time string comment '数据写入时间'
,biz_date string comment '分区字段'
) comment '整备项目'
stored as parquet
tblproperties("parquet.compress"="snappy");



drop table if exists ods.ods_dms_uc_uc_sales_contract;
create table if not exists ods.ods_dms_uc_uc_sales_contract(
id string comment '主键'
,sales_contract_serial string comment '销售合同编号'
,old_nominee_name string comment '旧名义人姓名'
,old_nominee_telephone string comment '旧名义人电话'
,old_nominee_id_card string comment '旧名义人身份证号码'
,old_nominee_address string comment '旧名义人住所'
,old_license_plate_number string comment '旧车牌号'
,sales_method string comment '销售方式'
,retail_customer_type string comment '零售客户类型'
,retail_customer_name string comment '零售客户姓名'
,retail_customer_id_card string comment '零售客户身份证号码'
,retail_customer_mobile_phone string comment '零售客户移动电话'
,retail_customer_telephone string comment '零售客户电话'
,retail_customer_postal_code string comment '零售客户邮编'
,retail_customer_address string comment '零售客户住所'
,customer_id string comment '客户ID'
,negotiation_id string comment '商谈ID'
,whsle_target_type string comment '批售对象类型'
,whsle_car_trader_id string comment '批售车商ID'
,whsle_dealer_code string comment '批售销售店代码'
,whsle_branch_code string comment '批售店铺代码'
,whsle_coop_platform_code string comment '批售合作平台代码'
,whsle_target_name string comment '批售对象名称'
,whsle_contact_name string comment '批售联系人名称'
,whsle_target_mobile_phone string comment '批售对象移动电话'
,whsle_target_telephone string comment '批售对象电话'
,whsle_target_address string comment '批售对象地址'
,whsle_target_postal_code string comment '批售对象邮编'
,whsle_target_email string comment '批售对象E-MAIL'
,vehicle_user_type string comment '车辆使用人类型'
,vehicle_user_name string comment '车辆使用人姓名'
,vehicle_user_id_card string comment '车辆使用人身份证号码'
,vehicle_user_mobile string comment '车辆使用人手机'
,vehicle_user_telephone string comment '车辆使用人电话'
,vehicle_user_postal_code string comment '车辆使用人邮编'
,vehicle_user_address string comment '车辆使用人地址'
,vehicle_body_price_income decimal(12,2) comment '车辆本体价格收入'
,vehicle_body_price_payment decimal(12,2) comment '车辆本体价格支出'
,discount decimal(12,2) comment '折扣'
,del_flag bigint comment '删除标识'
,create_by bigint comment '创建者'
,create_time string comment '创建时间'
,update_by bigint comment '更新者'
,update_time string comment '更新时间'
,remark string comment '备注'
,version bigint comment '版本号'
,dl_batch_id string comment 'dl加载批次'
,extract_time string comment '抽取表时的系统时间（以北京时间为标准时区时间）'
,load_time string comment '数据加载到hive的时间'
,source_system string comment '来源系统'
,insert_time string comment '数据写入时间'
,biz_date string comment '分区字段'
) comment '销售协议信息'
stored as parquet
tblproperties("parquet.compress"="snappy");



drop table if exists ods.ods_dms_uc_uc_sales_contract_cost;
create table if not exists ods.ods_dms_uc_uc_sales_contract_cost(
id string comment '主键'
,sales_contract_serial string comment '销售合同编号'
,cost_item_code string comment '费用项代码'
,cost_item_name string comment '费用项名称'
,cost_type string comment '费用类型'
,unit_price decimal(10,2) comment '单价'
,quantity bigint comment '数量'
,sales_price decimal(12,2) comment '销售价格'
,cost_item_cost_price decimal(12,2) comment '费用项成本价'
,del_flag bigint comment '删除标识'
,create_by bigint comment '创建者'
,create_time string comment '创建时间'
,update_by bigint comment '更新者'
,update_time string comment '更新时间'
,remark string comment '备注'
,version bigint comment '版本号'
,dl_batch_id string comment 'dl加载批次'
,extract_time string comment '抽取表时的系统时间（以北京时间为标准时区时间）'
,load_time string comment '数据加载到hive的时间'
,source_system string comment '来源系统'
,insert_time string comment '数据写入时间'
,biz_date string comment '分区字段'
) comment '销售合同费用'
stored as parquet
tblproperties("parquet.compress"="snappy");



drop table if exists ods.ods_dms_uc_uc_sales_ledger;
create table if not exists ods.ods_dms_uc_uc_sales_ledger(
id string comment '主键'
,sales_contract_serial string comment '销售合同编号'
,dealer_code string comment '销售店代码'
,branch_code string comment '店铺代码'
,vehicle_manage_no string comment '车辆管理编号'
,sales_status string comment '销售状态'
,sales_method string comment '销售方式'
,sales_sign_date string comment '销售签约日期'
,sales_sign_staff_account string comment '销售签约担当账号'
,temp_save_date string comment '临时保存日期'
,temp_save_staff_account string comment '临时保存担当账号'
,sales_total_income decimal(12,2) comment '销售总收入'
,sales_total_payment decimal(12,2) comment '销售总支付'
,payment_plan_date string comment '付款计划日期'
,payment_finish_date string comment '付款完成日期'
,invoice_number string comment '发票号'
,invoice_number_login_date string comment '发票号登录日期'
,authen_flag string comment '认证标识'
,uc_auth_no string comment '二手车认证编号'
,uc_auth_due_date string comment '二手车认证到期日'
,displace_flag string comment '置换标识'
,delivery_plan_date string comment '交车计划日期'
,delivery_finish_date string comment '交车完成日期'
,delivery_cancel_date string comment '交车取消日期'
,dealer_payment_transfer_cost decimal(12,2) comment '销售店支付过户费用'
,delivery_license_plate_number string comment '交车车牌号'
,sales_cancel_date string comment '销售取消日'
,sales_cancel_staff_account string comment '销售取消担当账号'
,del_flag bigint comment '删除标识'
,create_by bigint comment '创建者'
,create_time string comment '创建时间'
,update_by bigint comment '更新者'
,update_time string comment '更新时间'
,remark string comment '备注'
,version bigint comment '版本号'
,dl_batch_id string comment 'dl加载批次'
,extract_time string comment '抽取表时的系统时间（以北京时间为标准时区时间）'
,load_time string comment '数据加载到hive的时间'
,source_system string comment '来源系统'
,insert_time string comment '数据写入时间'
,biz_date string comment '分区字段'
) comment '二手车销售台账'
stored as parquet
tblproperties("parquet.compress"="snappy");



drop table if exists ods.ods_dms_cs_vhcl_common_model_grade_config;
create table if not exists ods.ods_dms_cs_vhcl_common_model_grade_config(
id string comment '主键'
,uc_franchise_code string comment '二手车品牌编号'
,uc_franchise_name string comment '二手车品牌名称'
,maker_code string comment '厂商代码'
,maker_name string comment '厂商名称'
,vehicle_model string comment '车型'
,vehicle_model_name string comment '车型名称'
,grade_name string comment '等级名称'
,vehicle_detail_config_id string comment '车辆详细配置ID'
,vehicle_detail_config_json string comment '车辆详细配置Json'
,sales_start_date string comment '销售开始日期'
,sales_end_date string comment '销售结束日期'
,vehicle_type_code string comment '车辆类型代码'
,vehicle_category_name string comment '车辆类型名称'
,new_vehicle_price decimal(12,2) comment '新车价格'
,exhaust string comment '排量'
,national_standard_model string comment '国标型号'
,leave_factory_time string comment '出厂时间'
,vehicle_model_publish_year string comment '车型发布年份'
,country_release_code string comment '国家公布代码'
,production_status string comment '生产状态'
,production_time string comment '生产时间'
,stop_production_time string comment '停产时间'
,vehicle_model_info string comment '车型信息'
,vehicle_model_category string comment '车型分类'
,gear_type string comment '档位类型'
,car_length string comment '车长'
,car_width string comment '车宽'
,car_height string comment '车高'
,vehicle_door_number_serial string comment '车门数编号'
,rate_allow_people_serial string comment '额定载客编号'
,discharge_standard_serial string comment '排放标准编号'
,gearbox_type string comment '变速箱类型'
,drive_method_serial string comment '驱动方式编号'
,energy_type_code string comment '能源类型代码'
,fuel_consumption string comment '油耗'
,whole_weight decimal(9,3) comment '整备质量'
,gearbox_category string comment '变速箱分类'
,gearbox_category_name string comment '变速箱分类名称'
,version bigint comment '版本号'
,create_time string comment '创建时间'
,update_by bigint comment '更新者'
,create_by bigint comment '创建者'
,update_time string comment '更新时间'
,del_flag bigint comment '删除标识'
,remark string comment '备注'
,dl_batch_id string comment 'dl加载批次'
,extract_time string comment '抽取表时的系统时间（以北京时间为标准时区时间）'
,load_time string comment '数据加载到hive的时间'
,source_system string comment '来源系统'
,insert_time string comment '数据写入时间'
,biz_date string comment '分区字段'
) comment '【通用车型】车辆等级配置信息'
stored as parquet
tblproperties("parquet.compress"="snappy");



drop table if exists ods.ods_dms_cs_salesed_vehicle_ledger;
create table if not exists ods.ods_dms_cs_salesed_vehicle_ledger(
id string comment '主键'
,customer_order_number string comment '客户订单号'
,car_owner_cert_number string comment '车主证件号码'
,car_owner_type string comment '车主类型'
,car_owner_name string comment '车主姓名'
,sales_dealer_code string comment '销售销售店代码'
,sales_company_name string comment '销售公司名称'
,sales_company_taxpayer_number string comment '销售公司统一信用代码'
,delivery_dealer_code string comment '交车销售店代码'
,sales_adviser_code string comment '销售顾问代码'
,delivery_consultant_code string comment '交车顾问代码'
,after_sales_adviser_code string comment '售后顾问代码'
,vinno string comment '车架号'
,vehicle_flag string comment '车辆区分'
,vehicle_type string comment '车辆类别'
,vinno_d7 string comment '车架号后7位'
,urn string comment '车辆生产识别码'
,vehicle_name string comment '车辆名称'
,vehicle_name_code string comment '车辆名称代码'
,vehicle_model_name string comment '车型名称'
,vehicle_model string comment '车型'
,stand_vehicle_model string comment '车型代码[标准]'
,vehicle_model_subdivision string comment '车型代码[细分]'
,vehicle_sfx_code string comment '车辆SFX代码'
,grade_code string comment '等级代码'
,grade_name string comment '等级名称（销售）'
,invoice_grade string comment '发票用车辆等级'
,invoice_vehicle_name string comment '发票用车型名称'
,vehicle_color_code string comment '车辆颜色代码'
,vehicle_color_name string comment '车辆颜色名称'
,interior_color_code string comment '内饰颜色代码'
,interior_color_name string comment '内饰颜色名称'
,engine string comment '发动机'
,engine_number string comment '发动机号(合格证)'
,engine_type string comment '发动机型号(合格证)'
,exhaust string comment '排量'
,gearbox string comment '变速箱'
,delivery_odometer_value decimal(10,2) comment '交车时公里数'
,vehicle_odometer_value decimal(10,2) comment '行驶公里数'
,vehicle_use string comment '车辆用途'
,sales_diff string comment '购买类型/销售区分'
,factory_code string comment '工厂代码'
,id_line string comment '生产线号'
,production_date string comment '制造日期'
,sales_price decimal(12,2) comment '销售价格'
,new_vehicle_retail_price decimal(12,2) comment '新车零售价格'
,fuel_type string comment '燃料种类'
,fuel_type_name string comment '燃料种类名称'
,final_inspt_date string comment '终检日'
,outday_date string comment '出门日'
,match_date string comment '匹配日'
,sales_date string comment '销售日'
,pds_date string comment 'PDS日'
,delivery_date string comment '交车日'
,warranty_status string comment '三包凭证更新状态'
,regist_number string comment '车牌号'
,vehicle_certificate_number string comment '整车合格证编号'
,invoice_number string comment '发票编号（销售）'
,del_flag bigint comment '删除标识'
,remark string comment '备注'
,create_time string comment '创建时间'
,create_by bigint comment '创建者'
,update_time string comment '更新时间'
,update_by bigint comment '更新者'
,vinno_after_6_digit string comment '车架号（后六位）'
,dl_batch_id string comment 'dl加载批次'
,extract_time string comment '抽取表时的系统时间（以北京时间为标准时区时间）'
,load_time string comment '数据加载到hive的时间'
,source_system string comment '来源系统'
,insert_time string comment '数据写入时间'
,biz_date string comment '分区字段'
) comment '已售车辆台账'
stored as parquet
tblproperties("parquet.compress"="snappy");



drop table if exists ods.ods_dms_cs_maintain_uc_repair_entrust;
create table if not exists ods.ods_dms_cs_maintain_uc_repair_entrust(
id string comment '主键'
,dealer_code string comment '销售店代码'
,branch_code string comment '店铺代码'
,vehicle_manage_no string comment '车辆管理编号'
,vinno string comment '车架号'
,repair_status string comment '整备状态'
,repair_type bigint comment '整备类型'
,dealer_repair_start_time string comment '销售店整备开始时间'
,dealer_repair_end_time string comment '销售店整备结束时间'
,user_pay_repair_cost decimal(12,2) comment '用户承担整备费用'
,dealer_repair_cost decimal(12,2) comment '销售店整备成本'
,repair_entrust_id string comment '整备委托ID'
,repair_entrust_date string comment '整备委托日期'
,repair_entrust_appraiser_code string comment '整备委托评估师代码'
,repair_entrust_memo string comment '整备委托留言'
,maintain_order_no string comment '维修工单号'
,maintain_order_accept_date string comment '维修工单受理日'
,maintain_order_start_date string comment '维修工单开始日'
,maintain_order_complete_date string comment '维修工单完成日'
,maintain_order_cancel_date string comment '维修工单取消日期'
,maintain_order_cancel_reason string comment '维修工单取消原因'
,maintain_order_settl_date string comment '维修工单结算日'
,maintain_order_settl_fee decimal(12,2) comment '维修工单结算费用'
,service_staff_account string comment '服务担当账号'
,nominee_type string comment '名义人类型'
,nominee_name string comment '名义人姓名'
,nominee_id_card string comment '名义人身份证号码'
,nominee_postal_code string comment '名义人邮编'
,nominee_telephone string comment '名义人电话'
,nominee_email string comment '名义人EMAIL'
,nominee_mobile_phone string comment '名义人手机号'
,uc_auth_flag string comment '二手车认证标识'
,uc_auth_no string comment '二手车认证编号'
,nominee_address string comment '名义人住所'
,create_time string comment '创建时间'
,create_by bigint comment '创建者'
,update_by bigint comment '更新者'
,update_time string comment '更新时间'
,del_flag bigint comment '删除标识'
,remark string comment '备注'
,dl_batch_id string comment 'dl加载批次'
,extract_time string comment '抽取表时的系统时间（以北京时间为标准时区时间）'
,load_time string comment '数据加载到hive的时间'
,source_system string comment '来源系统'
,insert_time string comment '数据写入时间'
,biz_date string comment '分区字段'
) comment '二手车整备委托'
stored as parquet
tblproperties("parquet.compress"="snappy");



drop table if exists ods.ods_dms_cs_meta_first_level_source;
create table if not exists ods.ods_dms_cs_meta_first_level_source(
id string comment '主键'
,source_code string comment '来源代码'
,source_name string comment '来源名称'
,create_by bigint comment '创建者'
,create_time string comment '创建时间'
,update_by bigint comment '更新者'
,update_time string comment '更新时间'
,del_flag bigint comment '删除标识'
,remark string comment '备注'
,dl_batch_id string comment 'dl加载批次'
,extract_time string comment '抽取表时的系统时间（以北京时间为标准时区时间）'
,load_time string comment '数据加载到hive的时间'
,source_system string comment '来源系统'
,insert_time string comment '数据写入时间'
,biz_date string comment '分区字段'
) comment '一级线索来源'
stored as parquet
tblproperties("parquet.compress"="snappy");



drop table if exists ods.ods_dms_cs_meta_second_level_source;
create table if not exists ods.ods_dms_cs_meta_second_level_source(
id string comment '主键'
,source_first_level_code string comment '一级来源代码'
,source_code string comment '来源代码'
,source_name string comment '来源名称'
,create_by bigint comment '创建者'
,create_time string comment '创建时间'
,update_by bigint comment '更新者'
,update_time string comment '更新时间'
,del_flag bigint comment '删除标识'
,remark string comment '备注'
,dl_batch_id string comment 'dl加载批次'
,extract_time string comment '抽取表时的系统时间（以北京时间为标准时区时间）'
,load_time string comment '数据加载到hive的时间'
,source_system string comment '来源系统'
,insert_time string comment '数据写入时间'
,biz_date string comment '分区字段'
) comment '二级线索来源'
stored as parquet
tblproperties("parquet.compress"="snappy");


